# Generated by Django 2.2.10 on 2020-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='professionals',
            field=models.ManyToManyField(blank=True, to='api.Professional'),
        ),
    ]
