# Generated by Django 2.2.10 on 2020-03-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200315_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
