# Generated by Django 2.2.10 on 2020-03-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200315_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='api.Service'),
            preserve_default=False,
        ),
    ]
