# Generated by Django 2.2.10 on 2020-04-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200330_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='professionals',
        ),
    ]
