# Generated by Django 2.2.10 on 2020-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_service_professionals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('S', 'Scheduled'), ('Y', 'Did attend'), ('N', 'Did not attend')], default='S', max_length=1),
        ),
    ]
